baseURL = "/"
title = "in-toto"
description = "A framework to secure the integrity of software supply chains"

enableRobotsTXT = true

theme = "docsy"

###############################################################################
# Docsy
###############################################################################
enableGitInfo = true

# language settings
contentDir = "content/en"
defaultContentLanguage = "en"
# tell Hugo not to include the /en/ element in the URL path for English docs
defaultContentLanguageInSubdir = false
# useful when translating
enableMissingTranslationPlaceholders = true
# disable taxonomies
disableKinds = ["taxonomy"]
# deprecated directories
ignoreFiles = []

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    # For MathJax
    # https://gohugo.io/content-management/mathematics/#setup
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    guessSyntax = "true"

###############################################################################
# Docsy - DrawIO configuration
###############################################################################
[params.drawio]
enable = true

###############################################################################
# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

###############################################################################
# Docsy - Services configuration
###############################################################################
[services]
  [services.googleAnalytics]
  id = "G-Y2KDEK0998"

###############################################################################
# Docsy - Language configuration
###############################################################################
[languages]
  [languages.en]
    title = "in-toto"
    languageName ="English"
    weight = 1

###############################################################################
# Docsy - Site Parameters
###############################################################################
[params]
  github_repo = "https://github.com/in-toto/in-toto.io"
  github_project_repo = "https://github.com/in-toto/in-toto"

  RSSLink = "/index.xml"
  author = "in-toto.org" # add your company name
  github = "in-toto" # add your github profile name

  copyright = "The in-toto Authors."
  trademark = "https://www.linuxfoundation.org/trademark-usage/"

  # Google Custom Search Engine ID.
  gcs_engine_id = "007239566369470735695:624rglujm-w"

  # Text label for the version menu in the top bar of the website.
  version_menu = "in-toto Version"

  # The major.minor version tag for the version of the docs represented in this
  # branch of the repository. Used in the "version-banner" partial to display a
  # version number for this doc set.
  version = "master"

  # Flag used in the "version-banner" partial to decide whether to display a
  # banner on every page indicating that this is an archived version of the docs.
  archived_version = false

  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = "https://in-toto.io/docs/"

  # A variable used in various docs to determine URLs for config files etc.
  # To find occurrences, search the repo for 'params "githubbranch"'.
  github_branch = "master"

  # Disable MathJax by default
  # NOTE: enable it per-page with `mathjax: true` in front matter
  mathjax = false
 
  # User interface configuration
  [params.ui]
    # Enable the logo
    navbar_logo = true
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Enable the search box in the side bar.
    sidebar_search_disable = true
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Show expand/collapse icon for sidebar sections
    sidebar_menu_foldable = true
    # Disable about button in footer
    footer_about_enable = false

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Glad to hear it! Please <a href="https://github.com/in-toto/in-toto.io/issues/new">tell us how we can improve</a>.'
        no = 'Sorry to hear that. Please <a href="https://github.com/in-toto/in-toto.io/issues/new">tell us how we can improve</a>.'

  # Links in footer
  [params.links]
    [[params.links.user]]
      name = "in-toto Slack"
      url = "https://slack.cncf.io/"
      icon = "fab fa-slack"
      desc = "Join the in-toto Slack Workspace!"
    [[params.links.user]]
      name = "in-toto Mailing List"
      url = "https://groups.google.com/g/in-toto-public"
      icon = "fa fa-envelope"
      desc = "Join the in-toto Mailing List!"
    [[params.links.user]]
      name = "in-toto Community Calendars"
      url = "https://tockify.com/cncf.public.events/monthly?search=in-toto"
      icon = "fa fa-calendar"
      desc = "View the in-toto Community Calendars!"